### ISSUE TITLE
now that checkpoints can be made persistent, need way to unpersist them

### ISSUE THREAD

**Issue by piccolbo** [RevolutionAnalytics/checkpoint#124]

**Comment by stefanfritsch** [comment]
Is there an ETA for this?

The lack of a way to "uncheckpoint" R easily is a real deal breaker on our end.

**Comment by revodavid** [comment]
@stefanfritsch can you explain in a little more detail what you want to happen during the "uncheckpoint" process? Hoping to learn more about what you and others may need in this case.

**Comment by stefanfritsch** [comment]
Hi,

thanks for your response. :)

We need just an easy way to undo what checkpoint does.

A user starts RStudio and all packages are missing because somebody had checkpoint running and saved that with the wrong workspace image.

ATM I don't know of any (end-user-workable) solution to get rid of it short of restarting R which is a very Windows 95 way of doing things. :) It can also be very time-consuming if data has to be read over the network.

Ideally there would be three functions

1. An easy way to check whether checkpoint is "running", i.e. controlling the library locations.
1. Restore the libraries as they were before `checkpoint(date)` was invoked. (This would probably require caching that information in the .checkpoint directory?)
2. Restore the libraries as they would be after a clean launch. (This would probably require parsing the start-up files?)

I know that it's not an entirely trivial feature request but it would remove the one major obstacle to using it here. 

Thanks
Stefan

**Comment by andrie** [comment]
I'll take a look at this.  We can cache the prior library location in memory or on disk and reset at request.

Assigning to myself.

**Comment by andrie** [comment]
Here is a simple fix:

Restore `.libPaths()` to point to `Sys.getenv("R_Libs_User")`

I will create a new function `unCheckpoint()` to do this.

**Comment by andrie** [comment]
The `unCheckpoint()` function is now available in the master branch on github.

Please test and provide feedback.

@stefanfritsch
