### ISSUE TITLE
Warning about unloading packages / error on installing dplyr and rgl

### ISSUE THREAD

**Issue by revodavid** [RevolutionAnalytics/checkpoint#155]
In the current dev version, I get the following warning every time I run the attached file:

```
Warning message:
‘magrittr’ namespace cannot be unloaded:
  namespace ‘magrittr’ is imported by ‘dplyr’ so cannot be unloaded 
```

It doesn't seem to cause any  problems, but maybe it could be avoided somehow so as not to concern the user.

[weather.R | uploaded via ZenHub](https://files.zenhub.io/54bfec05f748cd180f07a411)

**Comment by andrie** [comment]
This should be an easy fix to suppress the warning.  I shall take a look.

**Comment by andrie** [comment]
The script runs without problems in a *clean* session of R, but upon re-running twice in the same session, I get:

```r
> checkpoint("2015-01-21")
Scanning for loaded pkgs
Scanning for packages used in this project
Installing packages used in this project 
package ‘dplyr’ successfully unpacked and MD5 sums checked
package ‘tidyr’ successfully unpacked and MD5 sums checked
package ‘magrittr’ successfully unpacked and MD5 sums checked
package ‘ggplot2’ successfully unpacked and MD5 sums checked

Attaching package: ‘tidyr’

The following object is masked from ‘package:magrittr’:

    extract

Error in FUN(c("ggplot2", "magrittr", "tidyr", "dplyr")[[4L]], ...) : 
  there is no package called ‘dplyr’
In addition: Warning message:
‘magrittr’ namespace cannot be unloaded:
  namespace ‘magrittr’ is imported by ‘dplyr’ so cannot be unloaded 
```

**Comment by andrie** [comment]
So there are two issues here:

1. Warning when unloading a package if there is an reverse dependency, e.g. `magrittr` and `dplyr`
2. Unable to re-install some packages, e.g `dplyr`

It is easy to resolve the first using `suppressWarnings()`.

The second occurs because `dplyr` has a DLL that gets marked as in use.  The function `install.packages()` attempts to uninstall `dplyr` before re-installing, and this causes the error.

The fix is to check whether the required packages are already installed in the `.checkpoint` library.  If the package *is* installed, there is no reason to re-install, and installation should be skipped.  The reason is that an MRAN package on a given snapshot date can never change and be updated.  Thus, install once and never re-install.

Pinging @piccolbo

**Comment by revodavid** [comment]
Yes. `checkpoint` should determine the packages and versions that need to be installed for the project, and if the required version is already installed, do not attempt to reinstall it. This will make `checkpoint` faster on subsequent runs.
