### ISSUE TITLE
Tests fail with introduction of new R version

### ISSUE THREAD

**Issue by andrie** [RevolutionAnalytics/checkpoint#180]
R-3.2.0 was released a few days ago.  This change in version number causes some of the `checkpoint` unit tests to fail.

A short extract from the test log:

```
.....Error in get(method, envir = home) : 
  cannot open file 'C:/Users/Andrie de Vries/AppData/Local/Temp/Rtmpi6zlqe/.checkpoint/2014-10-01/lib/x86_64-w64-mingw32/3.2.0/MASS/R/MASS.rdb': No such file or directory
```

This log tells me that `checkpoint` is trying to install `MASS` from MRAN-server, for version R-3.2.0 on snapshot date 2014-10-01.

Now, of course, R-3.2.0 didn't exist at that date, thus the packages doesn't exist on the snapshot server.

**Comment by piccolbo** [comment]
One thing short term is to extract a reasonable date from R.version or packageDescription("base"), that is I think it's the test that's asking too much and need to be more flexible. Longer term, could we add some Rswitch-like capabilities? I don't have any experience running multiple versions of R. I hear it is possible.

**Comment by andrie** [comment]
I am still trying to characterize this problem. My current hypothesis is:

1. This has nothing to do with the `checkpoint` package itself. All tests pass for certain MRAN dates

2. During the transition period following April 16 (R-3.2.0 release date), not all files / packages on CRAN were properly uploaded. Specifically, some of the recommended packages are not on the MRAN snapshots until April 20th.

As evidence of point 2, compare the file listing on these pages:

* [MRAN 2015-04-16](http://mran.revolutionanalytics.com/snapshot/2015-04-16/bin/windows/contrib/3.2/) - notice no `MASS`
* [MRAN 2015-04-20](http://mran.revolutionanalytics.com/snapshot/2015-04-20/bin/windows/contrib/3.2/) - notice `MASS` now exists

I conclude that the package itself works fine, but inconsistencies exist on CRAN.

My current best plan of action is to find a selection of packages and shapshot dates that pass all tests on R-3.2.0 and resubmit for CRAN approval.

Copying @revodavid

**Comment by piccolbo** [comment]
We are wholly responsible for how checkpoint works irrespective of whether the problem is in CRAN, MRAN, the package itself, quantum physics, we own it.  All modern software depends on so many other resources and they all have bugs in them. That's no excuse. The manual is a promise to our users. We need to fix the package or maybe revise that promise, drop support for a week here or there and document it.  Cherry picking tests is turning testing into a mockery and doesn't solve anything but CRAN submission. Being on CRAN with a brittle package is not something I recommend. What are we going to say when the support issues start to pile up? Try a different date or packages?

Your initial analysis made sense, was marked by a confident "of course" and referred to 2014-10-1. The solution was to inhibit users from checkpointing to dates when their current R version did not exist. Your second analysis is more uncertain and refers to 2015-04-{16.20} , a much more recent set of dates on which R 3.2.0 existed. They seem like two completely separate problems to me. What am I missing?

Proposal: set earliest date for when a R release is supported. Any snapshot date after that should work. Use quickcheck's rDate to generate dates so that we can't cherry pick dates

```
rDate(elements = c(from = "2014-02-02", to = date()), size = ~10)
```
The from date should be the earliest for each R version when CRAN had all the base packages at least (needs a bit of maintenance, but not very often). So we would have something like

```
earliest.snapshot = 
  function (version)
    switch(version,
       3.2.0 = "2015-04-20",
       ...)
```

And then check and fail with a clear message when the request snapshot date is outside the supported range. Can it work?

**Comment by andrie** [comment]
Hi, Antonio

I agree with your sentiment.  We are responsible for the end-to-end solution.

The tests fails on **recommended** packages, and also occasionally on other packages, including foreach.  

There is something odd happening on CRAN (or MRAN, it's impossible for me to tell) around the cutover dates. Specifically, between April 16 (official release date) and April 20, some (possible all) recommended packages are missing from the snapshots.  For this range of dates, the current tests fail.

For the moment, it seems to me we are stuck with a range of dates where MRAN has an incomplete set of packages.

Your proposal isn't different in spirit than mine, only in implementation details.

We may have to do this, although it makes me uncomfortable, too.

**Comment by piccolbo** [comment]
I am not sure I understand the full implications. Right now, the earliest date for a snapshot with R version X.x is the first day X.x.0 was available (with failures). In the future, it may be a week later. Doesn't really bother me as much as it does you. Am I missing some of the implications? Cherry picking test data, that makes me extremely uncomfortable. Prof. knocking at my door. Jumping off a cliff. Any of the last three.

**Comment by andrie** [comment]
I'll be pushing some changes to the unit tests soon. These changes implement the suggestion by @piccolbo 

In short:

* Test for R version and adapt package start date accordingly
* For R-3.2 start tests at 2014-04-20

Also:

* Run tests one folder higher than `tempdir()`. In other words, create the checkpoint folder in `temp`, rather than a session specific subfolder.  This simply makes it easier to find the `.checkpoint` folder during debuggin.
