### ISSUE TITLE
Can't load MASS with current snapshots

### ISSUE THREAD

**Issue by stefanfritsch** [RevolutionAnalytics/checkpoint#185]
Hi,

there is an issue with newer MRAN snapshots; it works for 2015-07-02 but doesn't for 2015-07-13.

Basically if you restart R and run the code below you get the following error:

``` R
> checkpoint::checkpoint("2015-07-13")
Scanning for packages used in this project
  |=======================================================================================================================================| 100%
- Discovered 11 packages
All detected packages already installed
checkpoint process complete

---
> library(MASS)
Error in unloadNamespace(package) : 
  namespace ‘MASS’ is imported by ‘ggplot2’ so cannot be unloaded
In addition: Warning message:
package ‘MASS’ was built under R version 3.2.1 
Error in library(MASS) : Package ‘MASS’ version 7.3.41 cannot be unloaded

Restarting R session.
```
- This does not happen you change the date for the first time, i.e. when checkpoint still needs to install packages. Perhaps the check for packages loads them and then doesn't unload them correctly if the snapshot is newer?
- This does not happen with `checkpoint("2015-07-02")`
- Neither `search` nor the package list show either MASS or ggplot2 as loaded.
- This only happens with checkpoint, so checkpoint has to be involved somehow.

sessionInfo - basically RRO 3.2.0

``` R
> sessionInfo()
R version 3.2.0 (2015-04-16)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] Cairo_1.5-6      scales_0.2.5     ggplot2_1.0.1    readxl_0.1.0     lubridate_1.3.3  tidyr_0.2.0      magrittr_1.5     dplyr_0.4.2     
 [9] data.table_1.9.4 MASS_7.3-41     

loaded via a namespace (and not attached):
 [1] Rcpp_0.11.6       munsell_0.4.2     colorspace_1.2-6  R6_2.0.1          stringr_1.0.0     plyr_1.8.3        tools_3.2.0      
 [8] parallel_3.2.0    grid_3.2.0        gtable_0.1.2      DBI_0.3.1         lazyeval_0.1.10   checkpoint_0.3.10 digest_0.6.8     
[15] assertthat_0.1    reshape2_1.4.1    memoise_0.2.1     stringi_0.5-2     chron_2.3-47      proto_0.3-10     
```

Code:

```
options(stringsAsFactors = FALSE)

checkpoint::checkpoint("2015-07-13")

################################################################################
#
# Packages
#
################################################################################

library(MASS)

library(data.table)
library(dplyr)
library(magrittr)
library(tidyr)

library(lubridate)

library(readxl)

library(ggplot2)
library(scales)
library(Cairo)


```

**Comment by andrie** [comment]
Hi, Stefan

I am familiar with this issue, but have some trouble characterizing it.

What I do know is the following:

* Shortly after R-3.2.0 was released, some of the recommended packages (including MASS) had incorrect version numbers on CRAN, especially for the windows binary.

* You can confirm this by browsing to http://mran.revolutionanalytics.com/snapshot/2015-07-13/web/packages/MASS/index.html. Then hover your mouse over the windows binary and you'll notice that MASS was built for R-3.3 (instead of R-3.2). i.e. http://mran.revolutionanalytics.com/snapshot/2015-07-13/bin/windows/contrib/3.3/MASS_7.3-42.zip.

I don't know if this information is material yet.

Thank you for the additional information in your issue report. I'll take a careful look at this.

Andrie

**Comment by andrie** [comment]
One of the problems with `MASS` was that it explicitly depends on some base packages. Since one of the side effect of `checkpoint()` is to remove the `.Library` location from `.libPaths()` these dependencies could not be found when loading MASS.

In v0.4.0 I leave `.Library` in `.libPaths()` and I no longer experiene any problems or warnings when loading `MASS`.

I hope this is a general fix for this problem.

**Comment by fzenoni** [comment]
I hope this is the right place to post this. I am observing a similar problem when I load `knitr` when using `checkpoint` within a Markdown document. Please note that the whole approach detailed [here ](https://github.com/RevolutionAnalytics/checkpoint/blob/master/vignettes/archive/using-checkpoint-with-knitr.Rmd) was followed.

The error says:
```
Error in value[[3L]](cond) : 
  Package 'knitr' version 1.18 cannot be unloaded:
 Error in unloadNamespace(package) : namespace 'knitr' is imported by 'rmarkdown' so cannot be unloaded
Calls: <Anonymous> ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```

Also note that the problem occurs on Ubuntu 16.04, but **not** on Windows. Incidentally, the same occurs for `backports`.
```
Error in value[[3L]](cond) : 
  Package 'backports' version 1.1.2 cannot be unloaded:
 Error in unloadNamespace(package) : namespace 'backports' is imported by 'rprojroot' so cannot be unloaded
Calls: <Anonymous> ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```

**Comment by JulioV** [comment]
I have found the same problem as @fzenoni in Mac OS 10.15.2

`Error in value[[3L]](cond) : 
  Package 'knitr' version 1.26 cannot be unloaded:
 Error in unloadNamespace(package) : namespace 'knitr' is imported by 'rmarkdown' so cannot be unloaded
Calls: <Anonymous> ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted`

**Comment by Hong-Revo** [comment]
Installing over loaded packages should no longer be an issue in checkpoint v1.0.
