### ISSUE TITLE
Brand new install of MRO to try to fix this. 

### ISSUE THREAD

**Issue by jshousephd** [RevolutionAnalytics/checkpoint#249]
I even deleted all libraries.  Regardless of what date, checkpoint returns following error.

package ‘checkpoint’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\john\AppData\Local\Temp\RtmpmAMHHJ\downloaded_packages
> library(checkpoint)

checkpoint: Part of the Reproducible R Toolkit from Microsoft
https://mran.microsoft.com/documents/rro/reproducibility/
**> checkpoint("2017-08-20")
Error in authorizeFileSystemUse(checkpointLocation) : 
  promise already under evaluation: recursive default argument reference or earlier problems?
> checkpoint("2017-08-01")
Error in authorizeFileSystemUse(checkpointLocation) : 
  promise already under evaluation: recursive default argument reference or earlier problems?
> checkpoint("2017-06-01")
Error in authorizeFileSystemUse(checkpointLocation) : 
  promise already under evaluation: recursive default argument reference or earlier problems?**

**Comment by andrie** [comment]
You are using an old version of checkpoint. This has been fixed in the latest version of checkpoint.

I suggest you install the latest version of `checkpoint`.  You can also look in this duplicate bug report for other possible workarounds for older versions.

https://github.com/RevolutionAnalytics/checkpoint/issues/242
